In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, get_selected_arcs

In [3]:
#Import data
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])
beq = np.array([1, 0, 0, 0, 0, -1])
C = np.array([2, 1, 2, 5, 2, 1, 2])
Aub = [[3, 1, 3, 1, 3, 3, 5]]
bub = 9

In [5]:
# DATA transforming for optimization:
Aeq, arc_idxs, arc_idxs_list = nn2na(NN)
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

In [6]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [2 1 2 5 2 1 2] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq demand-supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



In [8]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, A_ub=Aub, b_ub=bub, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py:704: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  warn(redundancy_warning, OptimizeWarning)


In [9]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [0. 1. 0. 0. 1. 0. 1.]
The arcs that make the shortest path will be (from, to): [(0, 2), (2, 4), (4, 5)]
The minimum cost will be: 5.00 


In [15]:
bub = 8
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, A_ub=Aub, b_ub=bub, method='simplex')

In [16]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [0.2 0.8 0.  0.2 0.8 0.  0.8]
The arcs that make the shortest path will be (from, to): []
The minimum cost will be: 5.40 


En este caso observamos que al restringir el tiempo para recorrer el camino, el solver no encuentra solución factible.
Esto se evidencia en que las variables de decisión no son enteras. Esto es porque para hacer más "económica" la 
resolución, permitimos que el cálculo sea con variables continuas.