In [1]:
import numpy as np
from scipy.optimize import linprog
from ipynb.fs.full.functions import nn2na, get_selected_arcs

In [2]:
#Import data
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])
beq = np.array([1, 0, 0, 0, 0, -1])
C = np.array([2, 1, 2, 5, 2, 1, 2])
Aub = [[3, 1, 3, 1, 3, 3, 5]]
bub = 9

In [3]:
# DATA transforming for optimization:
Aeq, arc_idxs, arc_idxs_list = nn2na(NN)
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

In [4]:
print('## Optimizer inputs ## \n'
      'Cost vector: %s \n'
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds)) 

## Optimizer inputs ## 
Cost vector: [2 1 2 5 2 1 2] 
A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq demand-supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



In [5]:
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, A_ub=Aub, b_ub=bub, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  


In [6]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [0. 1. 0. 0. 1. 0. 1.]
The arcs that make the shortest path will be (from, to): [(0, 2), (2, 4), (4, 5)]
The minimum cost will be: 5.00 


In [7]:
bub = 8
# OPTIMIZE:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds, A_ub=Aub, b_ub=bub, method='simplex')

C:\Users\joaquin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
# GET THE SOLUTION:
selarcs = get_selected_arcs(arc_idxs, res.x)
print('## Results Using Simplex##')
print('The raw solution will be: %s' % res.x)
print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
print('The minimum cost will be: %0.2f ' % res.fun)

## Results Using Simplex##
The raw solution will be: [0.2 0.8 0.  0.2 0.8 0.  0.8]
The arcs that make the shortest path will be (from, to): []
The minimum cost will be: 5.40 


In this case we can see that when restricting our available time to "walk" the path, the solver does not find an acceptable solution. This is evident when we see the value of decision variables in the optimum: they are not integers. This happens because we never told the model not to take continuous values. 